### REGISTER
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name": "Amazon",
    "email": "amazon@gmail.com",
    "number": "9999999991",
    "password": "amazon",
    "role": "COMPANY"
}

### LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email":"amazon@gmail.com",
    "password": "amazon"
}

### LOGOUT
GET http://localhost:4000/api/auth/logout

### GET ME
GET http://localhost:4000/api/auth/me

### DELETE ACCOUNT (Requires Password)
POST http://localhost:4000/api/auth/delete
Content-Type: application/json

{
    "password": "student1"
}
